COLUNAS_OBRIGATORIAS = [
    "Material",
    "Texto breve material",
    "Lote",
    "Tipo de estoque",
    "Posição no depósito",
    "Depósito",
    "Tipo de depósito",
    "Ár.armazen.",
    "Unid.medida básica",
    "Estoque disponível",
    "Estoque p/armazenar",
    "Estoque saída depós.",
    "Estoque total",
    "Data da entrada de mercadorias",
    "Data do vencimento",
    "Último movimento",
    "Unidade de depósito",
    "Nº da ordem de transporte",
]